use serde::{Deserialize, Serialize};

// --- Response Wrapper ---
#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProductsSyncResponse {
    pub products: Vec<PosProduct>,
    // The API returns 'pagination', but we might not use it yet. 
    // We add it here so Serde doesn't get confused, but we can ignore it if we want.
    pub pagination: Option<Pagination>,
    // If your API sends the timestamp in the body, keep this. 
    // If it's missing in the JSON you pasted, we make it Option to prevent crashes.
    pub sync_timestamp: Option<String>, 
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Pagination {
    pub total: i32,
    pub pages: i32,
    pub page: i32,
    pub limit: i32,
}

// --- 1. Product ---
#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct PosProduct {
    pub product_id: String,
    
    // MAP JSON "name" -> Rust "product_name"
    #[serde(rename = "name")] 
    pub product_name: String,

    pub category: String,
    
    // Make optional as some products might not have images
    pub image_url: Option<String>, 
    
    // New field seen in your JSON
    pub total_stock: Option<i32>, 

    pub variants: Vec<Variant>,
}

// --- 2. Variant ---
#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Variant {
    pub variant_id: String,

    // MAP JSON "name" -> Rust "variant_name"
    // THIS FIXES YOUR ERROR (missing field `variantName`)
    #[serde(rename = "name")] 
    pub variant_name: String,

    pub sku: String,
    pub barcode: Option<String>,
    pub stock: i32,

    pub sellable_units: Vec<SellableUnit>,
}

// --- 3. Sellable Unit ---
#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct SellableUnit {
    pub unit_id: String,
    pub unit_name: String,
    pub price: f64,
    pub wholesale_price: Option<f64>, // Added based on your JSON
    pub conversion: f64,
    pub is_base_unit: bool,
    
    // Nested Pricing Rules
    pub pricing: Option<Vec<PricingRule>>, 
}

// --- 4. Pricing Rules ---
#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct PricingRule {
    pub price: f64,
    pub min_qty: i32,
    pub max_qty: Option<i32>, // Nullable in JSON
    pub list_id: String,
    pub list_name: String,
    pub list_code: String,
    pub priority: i32,
    
    // These dates can be null
    pub valid_from: Option<String>, 
    pub valid_to: Option<String>,   
}

// --- CUSTOMERS ---

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CustomersSyncResponse {
    pub data: Vec<PosCustomer>,
    pub next_sync_token: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct PosCustomer {
    pub id: String,
    pub name: String,
    pub email: Option<String>,
    pub phone: Option<String>,
    
    // Backend fields
    pub customer_type: Option<String>, // "B2B" or "B2C" usually
    pub company: Option<String>,
    pub business_account_id: Option<String>,
    pub loyalty_points: Option<f64>,
    
    // Computed/Frontend helper fields
    pub primary_address: Option<String>, 
    
    // Complex nested fields
    pub addresses: Option<Vec<CustomerAddress>>,
    pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct CustomerAddress {
    pub id: String,
    pub street1: String,
    pub city: String,
    pub postal_code: String,
}

// --- SALES ---

#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct QueuedSale {
    pub id: String,        // UUID generated by frontend
    pub timestamp: u64,
    pub location_id: String,
    pub transaction_data: serde_json::Value, // Flexible payload
    pub status: SaleStatus,
    pub retry_count: u32,
    pub last_error: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum SaleStatus {
    Pending,
    Syncing,
    Failed, // Fatal error (e.g., validation), don't retry
    Synced,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SaleResponse {
    pub success: bool,
    pub message: String,
    pub server_response: Option<serde_json::Value>,
}

// --- PRICING ---

#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct ClientPriceList {
    pub id: String,
    pub code: String,
    pub priority: i32,
    pub is_global: bool,
    pub is_active: bool,
    pub valid_from: Option<String>,
    pub valid_to: Option<String>,
    pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct ClientPriceListItem {
    pub id: String,
    pub price_list_id: String,
    pub variant_id: String,
    pub selling_unit_id: Option<String>,
    pub min_quantity: i32,
    pub price: String, // Keep as string to match API/Frontend precision if needed
    pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct PricingSyncResponse {
    pub metadata: PricingMetadata,
    pub data: PricingData,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct PricingMetadata {
    pub synced_at: String,
    pub is_delta: bool,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct PricingData {
    pub lists: Vec<ClientPriceList>,
    pub items: Vec<ClientPriceListItem>,
    pub customer_allocations: std::collections::HashMap<String, Vec<String>>,
    pub deleted_item_ids: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct PosPricingData {
    pub lists: Vec<ClientPriceList>,
    pub items: Vec<ClientPriceListItem>,
    pub allocations: std::collections::HashMap<String, Vec<String>>,
}